blog/apps/index/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/3/18 12:18
# @Author  : Aquarius
# @File    : urls.py
# @Software: PyCharm


from django.urls import path
from . import views
app_name = 'index'

urlpatterns = [
    path('', views.index, name="index"),
    path('book/<str:article_cate>/', views.book, name="book"),
    path('tech/<str:article_cate>/', views.tech, name="tech"),
    path('edit/<int:article_id>/', views.edit_page, name='edit'),
    path('edit/action/', views.edit_action, name='edit_action'),
    path('article/<int:article_id>/', views.text_page, name='article_page'),
]

blog/apps/videos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/3/23 12:03
# @Author  : Aquarius
# @File    : urls.py
# @Software: PyCharm


from django.urls import path
from . import views
app_name = 'index'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('face/', views.face, name="face"),
    path('phone/', views.phone, name="phone"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('apps.index.urls', 'blog'), namespace='blog')),
    path('videos/', include(('apps.videos.urls', 'blog'),namespace='videos')),
    path('admin/', admin.site.urls),  # username: admin  passworld: qwer1234
]

blog/apps/index/models.py
from django.db import models


# Create your models here.
# 数据迁移： python manage.py makemigrations
# 提交迁移：python manage.py migrate
# 生成数据表：python manage.py sqlmigrate 应用名 文件id 查看SQL语句


class Article(models.Model):
    'alter table tablename auto_increment=0'
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    category = models.CharField(max_length=16, default='美文')
    views = models.PositiveIntegerField('阅读量', default=0)

    def __str__(self):
        return self.title

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

blog/apps/videos/models.py
from django.db import models

# Create your models here.
# 数据迁移： python manage.py makemigrations
# 提交迁移：python manage.py migrate
# 生成数据表：python manage.py sqlmigrate 应用名 文件id 查看SQL语句


class Article(models.Model):
    image = models.CharField(max_length=32, default='Title')

blog/apps/index/views.py
from django.shortcuts import render
from . import models

# Create your views here.

def index(request):
    article = models.Article.objects.all()
    return render(request, 'index_web/index.html', {'article': article})


def book(request, article_cate):
    article = models.Article.objects.filter(category=article_cate)
    return render(request, 'index_web/book.html', {'article': article})


def tech(request, article_cate):
    article = models.Article.objects.filter(category=article_cate)
    return render(request, 'index_web/tech.html', {'article': article})


def text_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    article.views += 1
    article.save(update_fields=['views'])
    return render(request, 'index_web/pageinfo.html', {"article": article})


def edit_page(request, article_id):
    if str(article_id) == "99999999":
        return render(request, 'index_web/ed_article.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'index_web/ed_article.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    category = request.POST.get('category')
    article_id = request.POST.get('article_id')
    if article_id == '99999999':
        models.Article.objects.create(title=title, content=content, category=category)
        article = models.Article.objects.all()
        return render(request, 'index_web/index.html', {'article': article})
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.category = category
    article.save()
    return render(request, 'index_web/pageinfo.html', {"article": article})

blog/apps/videos/views.py
import base64
import json

from django.http import HttpResponse
from django.shortcuts import render
from .func.face import face_model
import re


# Create your views here.


def index(request):
    return render(request, 'video/demo.html')

def phone(request):
    return render(request, 'video/demo2.html')

def face(request):
    if request.method == 'POST':
        img = request.POST.get('image')
        print(img)
        print('长度：',len(img))
        # img_con = base64.b64decode(img[22:])
        if 'jpeg' in img[:25]:
            face = face_model(img[23:])  # 需要改为数据模式，不使用本地地址
        else:
            face = face_model(img[22:])
        res = face.get_face()
        print('结果返回值：')
        print(res)
        data = {}
        if res['error_msg'] == 'SUCCESS':
            data['error_msg'] = 'SUCCESS'
            for sku in res['result']['face_list']:
                data['id'] = sku['face_token']
                data['gender'] = '男' if sku['gender']['type'] == 'male' else '女'
                data['age'] = sku['age']
                emotion =  sku['emotion']['type']if sku['emotion']['type'] else 'neutral'
                em_data = {
                    'angry': '愤怒',
                    'disgust': '厌恶',
                    'fear': '恐惧',
                    'happy': '高兴',
                    'sad': '伤心',
                    'surprise': '惊讶',
                    'neutral': '无表情',
                    'pouty': '撅嘴',
                    'grimace': '鬼脸',
                }
                data['emotion'] = em_data[emotion]
                data['mask'] = '已佩戴' if sku['mask']['type'] == 1 else '未佩戴'
                return HttpResponse(json.dumps(data))
        else:
            data['error_msg'] = res['error_msg']
            return HttpResponse(json.dumps(data))

    return render(request, 'video/demo.html')

blog/templates/index_web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My blog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'index/content.css' %}">
    {% block css %}
        <link rel="stylesheet" type="text/css" href="#">
    {% endblock %}
    {% block js %}
        <scrip></scrip>
    {% endblock %}
</head>
<body>
<div class="header">
    <div class="blog_logo">
        <h1><a href="{% url 'blog:index' %}" style="color: #FFFFFF">Blog</a></h1>
    </div>
    <div class="nav">
        <ul class="menu">
            {% block menu %}
                <li class="active"><a href="{% url 'blog:index' %}">首页</a></li>
                <li><a href="{% url 'blog:tech' '技术' %}">技术分享</a></li>
                <li><a href="{% url 'blog:book' '美文' %}">美文欣赏</a></li>
                <li>
                    <div id="menu1">
                        <ul>
                            <li><a href="{% url 'videos:index' %}">人脸识别</a></li>
                            <li>图像识别</li>
                        </ul>
                    </div>
                </li>
{#                <a href="{% url 'videos:index' %}">小应用</a>#}
            {% endblock %}
        </ul>
    </div>
</div>


{% block main %}
    <div></div>
{% endblock %}
{% block new %}
<div class="news">
    <a href="{% url 'blog:edit' 99999999 %}">
        <img src="{% static 'index/add.png' %}" alt="新增文章" style="width: 55px;height: 55px">
    </a>
</div>
{% endblock %}

</body>
</html>

blog/templates/index_web/book.html
<!DOCTYPE html>
{% extends 'index_web/base.html' %}
{% block title %}美文欣赏{% endblock %}
{% block menu %}
    <li><a href="{% url 'blog:index' %}">首页</a></li>
    <li><a href="{% url 'blog:tech' '技术' %}">技术分享</a></li>
    <li class="active"><a href="{% url 'blog:book' '美文' %}">美文欣赏</a></li>
{% endblock %}
{% block main %}
    <div class="center_text">
        <div class="cent">
            <ul class="_all_blog">
                {% for blog_contente in article %}
                    <li class="_blog">
                        <p><a class="title"
                              href="{% url 'blog:article_page' blog_contente.id %}">{{ blog_contente.title }}</a></p>
                        <div class="content">
                            <span>{{ blog_contente.content|safe }}</span>
                        </div>
                        <div class="info">
                            <span id="cate">{{ blog_contente.category }} |</span>
                            <span>阅读量：({{ blog_contente.views }})</span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <footer class="footer">
        <div class="footer-1">

        </div>
        <div class="footer-2">
        </div>
    </footer>
{% endblock %}

blog/templates/index_web/ed_article.html
<!DOCTYPE html>
{% extends 'index_web/base.html' %}
{% block title %}文章撰写{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/edit.css' %}">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script type="text/javascript" src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'ueditor/lang/zh-cn/zh-cn.js' %}"></script>

{% endblock %}

{% block main %}
    <div class="editor_box">

        <form action="{% url 'blog:edit_action' %}" method="post" id="edit_form">
            {% csrf_token %}
            {% if article %}
                <div class="blog_title">
                    <input type="hidden" name="article_id" value="{{ article.id }}">
                    <label for="" class="edit_title">文章标题：
                        <input type="text" name="title" id="title" value="{{ article.title }}">
                    </label>
                    <br>
                    <label for="">文章类别：
                        <select name="category" id="">
                            <option value="技术">技术</option>
                            <option value="美文">美文</option>
                        </select>
                    </label><br>
                    <label for="" class="edit_content">文章内容：<br>
                        <script type="text/javascript">
                            //实例化编辑器
                            var ue = UE.getEditor('editor', {
                                'initialFrameHeight': 300,
                                'initialFrameWidth': 1000,
                                'topOffset': 20,
                                'initialContent': "{{ article.content|safe }}",
                            });
                        </script>
                        <input name="info" type="hidden" id="info">
                        <script id="editor" name="content" type="text/plain"></script>
                    </label>
                    <label for="" class="sub_button" style="cursor:pointer">
                        <input type="button" name="Submit" value=" 提交 " onClick="uptext()">
                        {#                    <input type="submit" width="100" value="发表文章" name="sub" onClick="upload()">#}
                    </label>
                    {#                <input type="button" width="100px" value="提交" onclick="upload()">#}
                </div>
            {% else %}
                <div class="blog_title">
                    <input type="hidden" name="article_id" value="99999999">
                    <label for="" class="edit_title">文章标题：
                        <input type="text" name="title" id="title">
                    </label>
                    <br>
                    <label for="">文章类别：
                        <select name="category" id="">
                            <option value="技术">技术</option>
                            <option value="美文">美文</option>
                        </select>
                    </label><br>
                    <label for="" class="edit_content">文章内容：<br>
                        <script type="text/javascript">
                            //实例化编辑器
                            var ue = UE.getEditor('editor', {
                                'initialFrameHeight': 300,
                                'initialFrameWidth': 1000,
                                'topOffset': 20,
                                'initialContent': "分享你的生活",
                            });
                        </script>
                        <script id="editor" name="content" type="text/plain"></script>
                    </label>
                    <label for="" class="sub_button" style="cursor:pointer">
                        <input name="info" type="hidden" id="info">
                        <input type="button" name="Submit" value=" 提交 " onClick="uptext()">
                    </label>
                </div>
            {% endif %}
            <script type="text/javascript">

                function uptext() {

                    var psel = document.getElementById("info");
                    var sub = document.getElementById("edit_form");
                    if (!UE.getEditor('editor').hasContents()) {
                        alert('请先填写内容!');
                    } else {
                        psel.value = UE.getEditor('editor').getContentTxt();
                        {#alert(s);#}
                        sub.submit();
                    }
                }
            </script>
        </form>
    </div>
{% endblock %}

blog/templates/index_web/index.html
<!DOCTYPE html>
{% extends 'index_web/base.html' %}

{% block main %}
    <div class="center_text">
        <div class="cent">
            <ul class="_all_blog">
                {% for blog_contente in article %}
                    <li class="_blog">
                        <p><a class="title"
                              href="{% url 'blog:article_page' blog_contente.id %}">{{ blog_contente.title }}</a></p>
                        <div class="content">
                            <span>{{ blog_contente.content|safe }}</span>
                        </div>
                        <div class="info">
                            <span id="cate">{{ blog_contente.category }} |</span>
                            <span>阅读量：({{ blog_contente.views }})</span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>

    </div>
    <footer class="footer">
        <div class="footer-1">
        </div>
        <div class="footer-2">
        </div>
    </footer>
{% endblock %}

blog/templates/index_web/pageinfo.html
<!DOCTYPE html>
{% extends 'index_web/base.html' %}
{% block title %}{{ article.title }}{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'index/page_css.css' %}">
{% endblock %}
{% block main %}
    <div class="art_main">
        <div class="title">
            <span>{{ article.title }}</span>
        </div>
        <div class="read">
            <p class="num">阅读量：({{ article.views }})</p>
            <p class="cate">关键字：{{ article.category }}</p>
        </div>
        <div class="art_content">
            <iframe width=100% frameborder=0 scrolling=auto
                    src='data:text/html;charset=UTF-8,{{ article.content }}'></iframe>
        </div>
        <a href="{% url 'blog:edit' article.id %}" style="color: #FFFFFF">
            <div class="edit">
                修改文章
            </div>
        </a>
    </div>
{% endblock %}

blog/templates/index_web/tech.html
<!DOCTYPE html>
{% extends 'index_web/base.html' %}
{% block title %}美食美客{% endblock %}
{% block menu %}
    <li><a href="{% url 'blog:index' %}">首页</a></li>
    <li class="active"><a href="{% url 'blog:tech' '技术' %}">技术分享</a></li>
    <li><a href="{% url 'blog:book' '美文' %}">美文欣赏</a></li>
{% endblock %}

{% block main %}
    <div class="center_text">
        <div class="cent">
            <ul class="_all_blog">
                {% for blog_contente in article %}
                    <li class="_blog">
                        <p><a class="title"
                              href="{% url 'blog:article_page' blog_contente.id %}">{{ blog_contente.title }}</a></p>
                        <div class="content">
                            <span>{{ blog_contente.content|safe }}</span>
                        </div>
                        <div class="info">
                            <span id="cate">{{ blog_contente.category }} |</span>
                            <span>阅读量：({{ blog_contente.views }})</span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <footer class="footer">
        <div class="footer-1">

        </div>
        <div class="footer-2">
        </div>
    </footer>
{% endblock %}

blog/templates/video/demo.html
<!DOCTYPE html>
{% extends 'index_web/base.html' %}
{% block title %}摄像头拍照{% endblock %}
{% block js %}
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block css %}
    <style type="text/css">
        #face_box {
            float: left;
            margin-top: 35px;
            text-align: center;
            width: 83%;
        }

        #video {
            float: left;
            margin-top: 35px;
            width: 600px;
            height: 400px;
        }

        .cam {
            float: left;
            margin-top: 25px;
            margin-left: 20px;
            width: 480px;
        }

        #canvas {
            float: left;
            margin-top: 35px;
            margin-left: 20px;
            border: 0.1px solid black;
        }

        #myTable {
            width: 300px;
            float: left;
            margin-left: 35px;
            text-align: center;

        }

        #myTable > th {
            width: 50px;
        }

        #myTable {
            width: 484px;
            table-layout: fixed;
            border: 1px;
            overflow: hidden;
        }

        #capture {
            width: 100px;
            height: 25px;
        }

        #sub {
            margin-left: 35px;
            width: 100px;
            height: 25px;
        }
        .black_overlay {
            display: none;
            position: absolute;
            top: 0%;
            left: 0%;
            width: 100%;
            height: 100%;
            background-color: black;
            z-index: 1001;
            -moz-opacity: 0.8;
            opacity: .80;
            filter: alpha(opacity=80);
        }

        .white_content {
            display: none;
            position: absolute;
			top: 28%;
			left: 30%;
			width: 40%;
			height: 30%;
			border: 16px solid lightblue;
			background-color: white;
			z-index: 1002;
			overflow: auto;
        }

    </style>
{% endblock %}
{% block menu %}
    <li><a href="{% url 'blog:index' %}">首页</a></li>
    <li><a href="{% url 'blog:tech' '技术' %}">技术分享</a></li>
    <li><a href="{% url 'blog:book' '美文' %}">美文欣赏</a></li>
    <li class="active">
        <div id="menu1">
            <ul>
                <li><a href="{% url 'videos:index' %}">人脸识别</a></li>
                <li>图像识别</li>
            </ul>
        </div>
    </li>
    {#                <a href="{% url 'videos:index' %}">小应用</a>#}
{% endblock %}
{% block main %}
    <div id="face_box">
        <video id="video" controls></video>
        <canvas id="canvas" width="480" height="320"></canvas>
        <div class="cam">
            <button id="capture">拍照</button>
            <button id="sub">提交</button>
            <br>
        </div>
        <div id="fade" class="black_overlay">
        </div>
        <div id="MyDiv" class="white_content">
            <div style="text-align: right; cursor: default; height: 40px;">
                <span style="font-size: 16px;" onclick="CloseDiv('MyDiv','fade')">关闭</span>
            </div>
            <table id="myTable" cellpadding="1" cellspacing="0" border="1">
                <caption align="top" style="margin-bottom: 15px">人脸识别结果</caption>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>性别</th>
                    <th>年龄</th>
                    <th>情绪</th>
                    <th>戴口罩了吗</th>
                </tr>
                </thead>
                <tbody id="tbMain">
                <tr>
                    <td id="t1" style="overflow:hidden;"></td>
                    <td id="t2"></td>
                    <td id="t3"></td>
                    <td id="t4"></td>
                    <td id="t5"></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% block new %}
    {% endblock %}
    <script>

        //访问用户媒体设备的兼容方法
        function getUserMedia(constrains, success, error) {
            if (navigator.mediaDevices.getUserMedia) {
                //最新标准API
                navigator.mediaDevices.getUserMedia(constrains).then(success).catch(error);
            } else if (navigator.webkitGetUserMedia) {
                //webkit内核浏览器
                navigator.webkitGetUserMedia(constrains).then(success).catch(error);
            } else if (navigator.mozGetUserMedia) {
                //Firefox浏览器
                navagator.mozGetUserMedia(constrains).then(success).catch(error);
            } else if (navigator.getUserMedia) {
                //旧版API
                navigator.getUserMedia(constrains).then(success).catch(error);
            }
        }

        var video = document.getElementById("video");
        var canvas = document.getElementById("canvas");
        var context = canvas.getContext("2d");

        //成功的回调函数
        function success(stream) {
            //兼容webkit内核浏览器
            var CompatibleURL = window.URL || window.webkitURL;
            //将视频流设置为video元素的源
            video.srcObject = stream;
            {#video.src = CompatibleURL.createObjectURL(stream);   // 此处的代码将会报错  解决的办法是将video的srcObject属性指向stream即可#}

            //播放视频
            video.play();
        }

        //异常的回调函数
        function error(error) {
            console.log("访问用户媒体设备失败：", error.name, error.message);
        }

        if (navigator.mediaDevices.getUserMedia || navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia) {
            //调用用户媒体设备，访问摄像头
            getUserMedia({video: {width: 480, height: 320}}, success, error);
        } else {
            alert("你的浏览器不支持访问用户媒体设备");
        }

        //注册拍照按钮的单击事件
        document.getElementById("capture").addEventListener("click", function () {
            //绘制画面
            context.drawImage(video, 0, 0, 480, 320);
        });

        //弹出隐藏层
        function ShowDiv(show_div, bg_div) {
            document.getElementById(show_div).style.display = 'block';
            document.getElementById(bg_div).style.display = 'block';
            var bgdiv = document.getElementById(bg_div);
            bgdiv.style.width = document.body.scrollWidth;
// bgdiv.style.height = $(document).height();
            $("#" + bg_div).height($(document).height());
        }

        //关闭弹出层
        function CloseDiv(show_div, bg_div) {
            document.getElementById(show_div).style.display = 'none';
            document.getElementById(bg_div).style.display = 'none';
        }

        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
        });

        document.getElementById('sub').addEventListener('click', function () {
            let data = canvas.toDataURL();
            console.log(data);

            $.ajax({
                url: "/videos/face/",
                type: 'post',
                data: {'image': data},
                success: function (result) {
                    var data = JSON.parse(result);
                    document.getElementById("t1").innerHTML = data.id;
                    document.getElementById("t2").innerHTML = data.gender;
                    document.getElementById("t3").innerHTML = data.age;
                    document.getElementById("t4").innerHTML = data.emotion;
                    document.getElementById("t5").innerHTML = data.mask;
                }
            });
            ShowDiv('MyDiv','fade')
        });


    </script>
{% endblock %}

blog/templates/video/demo2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="201801191" content="RHT">
    <title>Title</title>
</head>
<script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
<style type="text/css">
    #box2 {
        margin-left: -425px;
        float: left;
        margin-top: 156px;
        width: 360px;
        margin-right: 29px;
        height: 480px;
        background: #3b4249;
    }

    #box2 > img {
        width: 100%;
        height: 100%;
    }

    #myTable {
        width: 300px;
        float: left;
        margin-left: 131px;
        margin-top: 50px;
        text-align: center;

    }

    #myTable > th {
        width: 50px;
    }

    #myTable {
        width: 484px;
        table-layout: fixed;
        border: 1px;
        overflow: hidden;
    }

</style>
<body>

<div class="file-box" id="box">
    拍照上传
    <input type="file" accept="image/*" id="file_input" class="file-btn">
    <button type="button" id="sub" onclick="f()">提交</button>
</div>
<table id="myTable" cellpadding="1" cellspacing="0" border="1">
    <caption align="top" style="margin-bottom: 15px">人脸识别结果</caption>
    <thead>
    <tr>
        <th>ID</th>
        <th>性别</th>
        <th>年龄</th>
        <th>情绪</th>
        {#type 笑不笑#}
        <th>戴口罩了吗</th>
    </tr>
    </thead>
    <tbody id="tbMain">
    <tr>
        <td id="t1" style="overflow:hidden;"></td>
        <td id="t2"></td>
        <td id="t3"></td>
        <td id="t4"></td>
        <td id="t5"></td>
    </tr>
    </tbody>
</table>
<div id="box2">
    <img src="" id="showimg">
</div>
<script>
    var imginput = document.getElementById("file_input");
    var data = '';


    document.getElementById("box").onclick = function () {
        imginput.onchange = function () {
            var file = this.files[0];
            if (window.FileReader) {                                                        //如果浏览器支持FileReader
                var reader = new FileReader();                                         //新建一个FileReader对象
                reader.readAsDataURL(file);                                            //读取文件url
                reader.onloadend = function (e) {
                    console.log(e);//输出e,查看其参数
                    console.log(e.target.result);//通过e,输出图片的base64码
                    data = e.target.result;
                    $("#showimg").attr("src", e.target.result);//将base64码填入src,用于预览
                }
            }

        }

    };
    $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
    });

    function f() {
        $.ajax({
            url: "/videos/face/",
            type: 'post',
            data: {'image': data},
            success: function (result) {
                var data = JSON.parse(result);
                if (data.id) {
                    document.getElementById("t1").innerHTML = data.id;
                    document.getElementById("t2").innerHTML = data.gender;
                    document.getElementById("t3").innerHTML = data.age;
                    document.getElementById("t4").innerHTML = data.emotion;
                    document.getElementById("t5").innerHTML = data.mask;
                }
                else {
                    alert(data.error_msg);
                }
            }
        })
    }


</script>
</body>
</html>

blog/templates/video/demo3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="201801191" content="RHT">
    <title>Title</title>
</head>
<body>
<video
        id="webcam"
        :style="videoStyle"
        :width="videoWidth"
        :height="videoHeight"
        loop
        preload
>
</video>
<script>
     initVideo(){
      let that = this;
      this.video = document.getElementById("webcam");
      setTimeout(() => {
        if (
          navigator.mediaDevices.getUserMedia ||
          navigator.getUserMedia ||
          navigator.webkitGetUserMedia ||
          navigator.mozGetUserMedia
        ) {
          //调用用户媒体设备, 访问摄像头
          this.getUserMedia(
            {
              video: {
                width: {
                  ideal: that.videoWidth,
                  max: that.videoWidth
                },
                height: {
                  ideal: that.videoHeight,
                  max: that.videoHeight
                },
                facingMode: "user",    //前置摄像头
                frameRate: {
                  ideal: 30,
                  min: 10
                }
              }
            },
            this.videoSuccess,
            this.videoError
          );
        } else {
          this.$toast.center("摄像头打开失败,请检查权限设置!");
        }
      }, 300);
    },
     getUserMedia(constraints, success, error) {
      if (navigator.mediaDevices.getUserMedia) {
        //最新的标准API
        navigator.mediaDevices
          .getUserMedia(constraints)
          .then(success)
          .catch(error);
      } else if (navigator.webkitGetUserMedia) {
        //webkit核心浏览器
        navigator.webkitGetUserMedia(constraints, success, error);
      } else if (navigator.mozGetUserMedia) {
        //firfox浏览器
        navigator.mozGetUserMedia(constraints, success, error);
      } else if (navigator.getUserMedia) {
        //旧版API
        navigator.getUserMedia(constraints, success, error);
      }
    },
    videoSuccess(stream) {
      this.mediaStreamTrack = stream;
      this.video.srcObject = stream;
      this.video.play();
    },
    videoError(error) {
      console.error(error);
      this.$toast.center("摄像头打开失败,请检查权限设置!");
    },
</script>
</body>
</html>